### ISSUE TITLE
testing on custom  data

### ISSUE THREAD

**Issue by random-guest** [idiap/ESLAM#3]
Congrats on the impressive work!

Is it possible to test ESLAM on data obtained from a commercial RGBD camera like Intel Realsense or Kinect?

I tried using the config file for TUM RGBD, after I have prepared the rgb.txt and depth.txt files, and the corresponding depth and rgb folders, and I also changed the width and hight and the intrinsic parameters as well, but I got the following error:

Traceback (most recent call last):
  File "run.py", line 65, in <module>
    main()
  File "run.py", line 60, in main
    eslam = ESLAM(cfg, args)
  File "/home/desk/my_WorkingDirectory/Neural Implicit-Based SLAM/Depth-Based/ESLAM/src/ESLAM.py", line 105, in __init__
    self.frame_reader = get_dataset(cfg, args, self.scale)
  File "/home/desk/my_WorkingDirectory/Neural Implicit-Based SLAM/Depth-Based/ESLAM/src/utils/datasets.py", line 71, in get_dataset
    return dataset_dict[cfg['dataset']](cfg, args, scale, device=device)
  File "/home/desk/my_WorkingDirectory/Neural Implicit-Based SLAM/Depth-Based/ESLAM/src/utils/datasets.py", line 193, in __init__
    self.input_folder, frame_rate=32)
  File "/home/desk/my_WorkingDirectory/Neural Implicit-Based SLAM/Depth-Based/ESLAM/src/utils/datasets.py", line 233, in loadtum
    pose_data = self.parse_list(pose_list, skiprows=1)
UnboundLocalError: local variable 'pose_list' referenced before assignment

It seems like I should also pass the ground-truth poses (?)

Any advice would be highly appreciated!
Thank you in advance for your time

**Comment by MohammadJohari** [comment]
Hello,

You can remove all parts of the source code that requires ground truth poses as they are only used for evaluation.
However, you should be careful about the initialization of the camera pose and the scene bounds defined in the config files. Note that we use the ground truth pose for the first frame and only track the camera poses for the rest of the camera poses. This means that you can define an arbitrary camera pose for the first frame, but you need to be careful to set the scene bounds based on that arbitrary camera pose such that the feature planes could cover the whole interesting regions in the scene.

I hope this helps.
